#!/usr/bin/env python3
"""Generate a Pyrogram session string for the assistant userbot — and save it.

The old version printed the string and left you to copy it into .env by hand,
which is both a chore and the easiest way to leak a credential (it lands in
your terminal scrollback, and from there into screenshots and pastes).

This version reads API_ID / API_HASH / BOT_TOKEN from .env, logs the assistant
in, and writes SESSION_STRING straight back to .env with a backup of the
previous file. Nothing secret is printed unless you ask for it.

    python session_generator.py                 # interactive, saves to .env
    python session_generator.py --print         # also show the string
    python session_generator.py --env prod.env  # write somewhere else
    python session_generator.py --check         # validate the saved one

Telegram may invalidate a session when an account signs in elsewhere or the
user terminates it from Settings → Devices, so this is a thing you will run
more than once. It is written to be re-runnable.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import re
import shutil
import sys
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - dependency is in requirements.txt
    print("python-dotenv is missing. Run: pip install -r requirements.txt")
    sys.exit(1)


ENV_KEY = "SESSION_STRING"
DEFAULT_ENV = ".env"


# ── .env editing ───────────────────────────────────────────────────────────
def write_env_value(path: Path, key: str, value: str) -> str:
    """Set ``key`` in a .env file, preserving everything else.

    Returns a one-word description of what happened: created, updated or
    appended. The file is rewritten in place rather than regenerated so
    comments, ordering and unrelated keys survive — losing someone's
    hand-edited config to save one credential would be a poor trade.
    """
    if not path.exists():
        path.write_text(f"{key}={value}\n")
        _secure(path)
        return "created"

    # Back up before touching it. Cheap, and the one time it matters is the
    # time the process dies halfway through a write.
    backup = path.with_suffix(path.suffix + ".bak")
    shutil.copy2(path, backup)

    lines = path.read_text().splitlines()
    pattern = re.compile(rf"^\s*(export\s+)?{re.escape(key)}\s*=", re.IGNORECASE)
    replaced = False
    for index, line in enumerate(lines):
        match = pattern.match(line)
        if match:
            # Keep an `export ` prefix if the file uses one: some people
            # source their .env in a shell, and dropping it silently breaks
            # that without touching anything they would think to check.
            prefix = "export " if match.group(1) else ""
            lines[index] = f"{prefix}{key}={value}"
            replaced = True
            break

    if not replaced:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# Assistant session, generated by session_generator.py")
        lines.append(f"{key}={value}")

    path.write_text("\n".join(lines) + "\n")
    _secure(path)
    return "updated" if replaced else "appended"


def _secure(path: Path) -> None:
    """Make the file owner-only. Best effort: Windows has no chmod that means this."""
    try:
        path.chmod(0o600)
    except OSError:
        pass


def _warn_if_tracked(path: Path) -> None:
    """Shout if the target file is under version control.

    .gitignore covers *.env, but --env accepts any path. Writing a session
    string into a tracked file is the kind of mistake you only notice after
    it is pushed, so it is worth a check rather than an assumption.
    """
    import subprocess

    try:
        result = subprocess.run(
            ["git", "check-ignore", "-q", str(path)],
            capture_output=True,
            timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return  # no git, or not a repo — nothing to warn about

    if result.returncode == 0:
        return  # ignored, which is what we want

    tracked = subprocess.run(
        ["git", "ls-files", "--error-unmatch", str(path)],
        capture_output=True,
        timeout=5,
    )
    if tracked.returncode == 0:
        print()
        print("  ⚠️  WARNING")
        print(f"     {path} is TRACKED BY GIT. A session string written here")
        print("     will be committed and can be read by anyone with repo")
        print("     access. Add it to .gitignore before you push.")
        print()


def mask(secret: str, keep: int = 6) -> str:
    if len(secret) <= keep * 2:
        return "*" * len(secret)
    return f"{secret[:keep]}…{secret[-keep:]}  ({len(secret)} chars)"


# ── credentials ────────────────────────────────────────────────────────────
def read_credentials(env_path: Path) -> tuple[int, str]:
    """Load API_ID/API_HASH from the env file, prompting only if absent."""
    load_dotenv(env_path if env_path.exists() else None)

    raw_id = (os.getenv("API_ID") or "").strip()
    api_hash = (os.getenv("API_HASH") or "").strip()

    if not raw_id:
        raw_id = input("API_ID (from https://my.telegram.org): ").strip()
    if not api_hash:
        api_hash = input("API_HASH: ").strip()

    try:
        api_id = int(raw_id)
    except ValueError:
        print(f"\n✖ API_ID must be a number, got {raw_id!r}.")
        sys.exit(1)
    if not api_id or not api_hash:
        print("\n✖ API_ID and API_HASH are both required.")
        print("  Get them from https://my.telegram.org → API development tools.")
        sys.exit(1)
    return api_id, api_hash


# ── the two things this script does ────────────────────────────────────────
async def generate(env_path: Path, *, show: bool) -> int:
    from pyrogram import Client

    api_id, api_hash = read_credentials(env_path)

    print()
    print("═" * 58)
    print("  Ultimate Music Bot — assistant session generator")
    print("═" * 58)
    print()
    print("  Sign in as the ASSISTANT account, not the bot.")
    print("  This is an ordinary user account that joins voice chats")
    print("  to stream audio. Do not use your personal account if you")
    print("  can avoid it — the session string grants full access.")
    print()
    print(f"  API_ID {api_id} · writing to {env_path}")
    print("─" * 58)
    print()

    try:
        async with Client(
            "assistant_session", api_id=api_id, api_hash=api_hash, in_memory=True
        ) as app:
            session_string = await app.export_session_string()
            me = await app.get_me()
    except Exception as exc:
        print(f"\n✖ Login failed: {type(exc).__name__}: {exc}")
        print("  Common causes: wrong API_ID/API_HASH pair, a mistyped code,")
        print("  or 2FA enabled without the password to hand.")
        return 1

    _warn_if_tracked(env_path)
    action = write_env_value(env_path, ENV_KEY, session_string)

    label = f"@{me.username}" if me.username else (me.first_name or str(me.id))
    print()
    print("─" * 58)
    print(f"  ✔ Signed in as {label}  (id {me.id})")
    print(f"  ✔ {ENV_KEY} {action} in {env_path}")
    print(f"    {mask(session_string)}")
    if action == "updated":
        print(f"  ✔ previous file backed up to {env_path.name}.bak")
    print("─" * 58)
    print()

    if show:
        print("SESSION_STRING (keep this secret):")
        print(session_string)
        print()
    else:
        print("  The string was not printed. Use --print if you need it,")
        print("  e.g. to paste into a Render environment variable.")
        print()

    print("  Next: make sure the assistant account has joined, or can join,")
    print("  the groups you want to play in. Then restart the bot.")
    print()
    return 0


async def check(env_path: Path) -> int:
    """Validate the saved session string by connecting with it."""
    from pyrogram import Client

    load_dotenv(env_path if env_path.exists() else None)
    session_string = (os.getenv(ENV_KEY) or "").strip()
    if not session_string:
        print(f"✖ No {ENV_KEY} found in {env_path}. Run without --check first.")
        return 1

    api_id, api_hash = read_credentials(env_path)
    print(f"Checking the session in {env_path} …")
    try:
        async with Client(
            "assistant_check",
            api_id=api_id,
            api_hash=api_hash,
            session_string=session_string,
            in_memory=True,
        ) as app:
            me = await app.get_me()
    except Exception as exc:
        print(f"✖ The saved session is not usable: {type(exc).__name__}: {exc}")
        print("  Re-run this script without --check to generate a fresh one.")
        return 1

    label = f"@{me.username}" if me.username else (me.first_name or str(me.id))
    print(f"✔ Valid — signed in as {label} (id {me.id})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate and save a Pyrogram session string for the assistant."
    )
    parser.add_argument(
        "--env", default=DEFAULT_ENV, help=f"env file to write (default: {DEFAULT_ENV})"
    )
    parser.add_argument(
        "--print",
        dest="show",
        action="store_true",
        help="also print the session string (it is hidden by default)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the session already saved in the env file",
    )
    args = parser.parse_args()

    env_path = Path(args.env).expanduser()
    try:
        if args.check:
            return asyncio.run(check(env_path))
        return asyncio.run(generate(env_path, show=args.show))
    except KeyboardInterrupt:
        print("\nCancelled — nothing was written.")
        return 130


if __name__ == "__main__":
    sys.exit(main())
